-- 코드를 입력하세요
SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM DOCTOR D, PATIENT P, APPOINTMENT A
WHERE A.PT_NO = P.PT_NO
AND A.MDDR_ID = D.DR_ID
AND A.APNT_YMD >= TO_TIMESTAMP('2022-04-13 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
AND A.APNT_YMD <  TO_TIMESTAMP('2022-04-14 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
AND A.APNT_CNCL_YN = 'N'
AND A.MCDP_CD = 'CS'
ORDER BY APNT_YMD;