SELECT B.TITLE, R.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS B JOIN USED_GOODS_REPLY AS R USING (BOARD_ID)
WHERE B.BOARD_ID IN (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    WHERE CREATED_DATE >= '2022-10-01' AND CREATED_DATE <= '2022-10-31'
)
ORDER BY R.CREATED_DATE, B.TITLE;